[tool.black]
line-length = 88
target-version = ['py39']

[tool.pylint.BASIC]
ignored-modules='format, auth'
good-names = [
    "i",
    "e",
    "logger",
    # variables we want to match with
    # the frontend (TS) conventions
    "researcherID",
    "datasetID",
    "datapointID",
]

[tool.pylint.messages_control]
disable = "C0116, C0115, C0114"
init-hook="import sys; sys.path.append('src/libraries/python/')"

[tool.pylint.format]
max-line-length = "100"


[tool.pyright]
extraPaths = ["src/libraries/python/"]
