version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "pharos-api-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qyq7zg39j1iy"
s3_prefix = "pharos-api-dev"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = "CorsAllow=\"*\" UsersTableName=\"users\" DatasetsTableName=\"datasets2\" ProjectsTableName=\"projects\" LayerName=\"layer\""
image_repositories = []

[review]
[review.deploy]
[review.deploy.parameters]
stack_name = "pharos-api-review"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qyq7zg39j1iy"
s3_prefix = "pharos-api-review"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = "CorsAllow=\"https://review-pharos-frontend.talusanalytics.com\" UsersTableName=\"users\" DatasetsTableName=\"datasets2\" ProjectsTableName=\"projects\" LayerName=\"layer\""
image_repositories = []


[prod]
[prod.deploy]
[prod.deploy.parameters]
stack_name = "pharos-api-prod"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qyq7zg39j1iy"
s3_prefix = "pharos-api-prod"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = "CorsAllow=\"https://prod-pharos-frontend.talusanalytics.com\" UsersTableName=\"users\" DatasetsTableName=\"datasets\" ProjectsTableName=\"projects\" LayerName=\"layer\""
image_repositories = []

[staging]
[staging.deploy]
[staging.deploy.parameters]
stack_name = "pharos-api-staging"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1qyq7zg39j1iy"
s3_prefix = "pharos-api-staging"
region = "us-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "CorsAllow=\"https://staging-pharos-frontend.talusanalytics.com\" UsersTableName=\"users\" DatasetsTableName=\"datasets\" ProjectsTableName=\"projects\" LayerName=\"layer\""
image_repositories = []
