version = 0.1
[dev]
[dev.deploy]
[dev.deploy.parameters]
stack_name = "pharos-api-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-c378ct86r2s3"
s3_prefix = "pharos-api-dev"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = "CorsAllow=\"https://dev-pharos-frontend.talusanalytics.com\""
image_repositories = []

[review]
[review.deploy]
[review.deploy.parameters]
stack_name = "pharos-api-review"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-c378ct86r2s3"
s3_prefix = "pharos-api-review"
region = "us-east-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
parameter_overrides = "CorsAllow=\"https://review-pharos-frontend.talusanalytics.com\""
image_repositories = []
