AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  pharos-api

  Sample SAM Template for pharos-api

Parameters:
  CorsAllow:
    Type: String
    Default: "http://localhost:8000"
  UsersTableName:
    Type: String
    Default: users
  DatasetsTableName:
    Type: String
    Default: datasets
  ProjectsTableName:
    Type: String
    Default: projects
  LayerName:
    Type: String
    Default: layer
  DatasetsS3Bucket:
    Type: String
    Default: bucket
  NVersions:
    Type: String
    Default: 5
  RDSProxyName:
    Type: String
    Default: proxy
  RDSProxyPolicyName:
    Type: String
    Default: proxy-policy
  RDSProxyUserName:
    Type: String
    Default: database-user
  RDSProxyEndpointName:
    Type: String
    Default: proxy-endpoint
  SubnetIDs:
    Type: String
  DBInstance:
    Type: String
  VPCId:
    Type: String
  VPCSG:
    Type: String
  SecretRDS:
    Type: String
  Host:
    Type: String
  Database:
    Type: String
  Port:
    Type: String
  Username:
    Type: String

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
    Runtime: python3.9
    Architectures:
      - x86_64
    Handler: app.lambda_handler
  Api:
    Cors: !Join ["", ["'", !Ref CorsAllow, "'"]]
    TracingEnabled: True

Resources:
  RDSProxy:
    Type: AWS::RDS::DBProxy
    Properties:
      Auth:
        - AuthScheme: SECRETS
          IAMAuth: REQUIRED
          SecretArn: !Ref SecretRDS
      DBProxyName: !Join ["-", [!Ref AWS::StackName, !Ref RDSProxyName]]
      EngineFamily: POSTGRESQL
      IdleClientTimeout: 600
      DebugLogging: True
      RequireTLS: True
      RoleArn: !GetAtt RDSProxyRole.Arn
      VpcSubnetIds: !Split [",", !Ref SubnetIDs]
      # VpcSecurityGroupIds:
      #   - !Ref VPCSecurityGroup

  RDSProxyRole: #IAM role to be associated with the RDS Proxy.
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRole
            Principal:
              Service:
                - rds.amazonaws.com
      Policies:
        - PolicyName:
            !Join ["-", [!Ref AWS::StackName, !Ref RDSProxyPolicyName]]
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - !Ref SecretRDS
              - Effect: Allow
                Action: "kms:Decrypt"
                Resource: "*" #TODO make more specific !Sub "arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*"
                Condition:
                  StringEquals:
                    kms:ViaService: secretsmanager.us-east-2.amazonaws.com

  ProxyTargetGroup:
    Type: AWS::RDS::DBProxyTargetGroup
    Properties:
      DBProxyName: !Join ["-", [!Ref AWS::StackName, !Ref RDSProxyName]]
      DBInstanceIdentifiers:
        - !Ref DBInstance # TODO DB instance identifiers.
      TargetGroupName: default
      ConnectionPoolConfigurationInfo:
        MaxConnectionsPercent: 30 # Limit to 30% of db max connections
        MaxIdleConnectionsPercent: 12
        ConnectionBorrowTimeout: 20 # The number of seconds for a proxy to wait for a connection to become available in the connection pool. Only applies when the proxy has opened its maximum number of connections and all connections are busy with client sessions.
    DependsOn: RDSProxy

  Libraries:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: src/libraries/
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Delete
      Description: Provides the base backend shared library and dependencies
      LayerName: !Join ["-", [!Ref AWS::StackName, !Ref LayerName]]
  
  Database:
    Type: AWS::Serverless::LayerVersion
    Properties:
    ContentUri: src/postgresql
      CompatibleRuntimes:
        - python3.9
      RetentionPolicy: Delete
      Description: Provides libraries and dependencies for rds connectivity
      LayerName: !Join ["-", [!Ref AWS::StackName, database]]

  UsersTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: "researcherID"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "researcherID"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"
      TableName: !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]

  DatasetsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: "datasetID"
          AttributeType: "S"
        - AttributeName: "recordID"
          AttributeType: "S"
      KeySchema: # DynamoDB does not index data if primary key is not partition+sort hence unable to query
        - AttributeName: "datasetID"
          KeyType: "HASH" # Partition key
        - AttributeName: "recordID"
          KeyType: "RANGE" # Sort Key
      BillingMode: "PAY_PER_REQUEST"
      TableName: !Join ["-", [!Ref AWS::StackName, !Ref DatasetsTableName]]

  ProjectsTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: "projectID"
          AttributeType: "S"
      KeySchema: # DynamoDB does not index data if primary key is not partition+sort hence unable to query
        - AttributeName: "projectID"
          KeyType: "HASH" # Partition key
      BillingMode: "PAY_PER_REQUEST"
      TableName: !Join ["-", [!Ref AWS::StackName, !Ref ProjectsTableName]]

  DatasetsS3:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join ["-", [!Ref AWS::StackName, !Ref DatasetsS3Bucket]]
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  GetUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    DependsOn: UsersTable
    Properties:
      CodeUri: src/lambda/auth/
      Events:
        Auth:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /auth
            Method: post
      Layers:
        - !Ref Libraries
      Environment:
        Variables:
          CORS_ALLOW: !Ref CorsAllow
          USERS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]

  CreateUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    DependsOn: UsersTable
    Properties:
      CodeUri: src/lambda/create_user/
      Events:
        Auth:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /create-user
            Method: post
      Layers:
        - !Ref Libraries
      Environment:
        Variables:
          CORS_ALLOW: !Ref CorsAllow
          USERS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]

  SaveDatasetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    DependsOn:
      - UsersTable
      - DatasetsTable
    Properties:
      CodeUri: src/lambda/save_dataset/
      Events:
        Auth:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /save-dataset
            Method: post
      Layers:
        - !Ref Libraries
      Environment:
        Variables:
          CORS_ALLOW: !Ref CorsAllow
          USERS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
          DATASETS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref DatasetsTableName]]
          PROJECTS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref ProjectsTableName]]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
        - DynamoDBCrudPolicy:
            TableName:
              !Join ["-", [!Ref AWS::StackName, !Ref DatasetsTableName]]
        - DynamoDBCrudPolicy:
            TableName:
              !Join ["-", [!Ref AWS::StackName, !Ref ProjectsTableName]]

  ListDatasetFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    DependsOn:
      - UsersTable
      - DatasetsTable
    Properties:
      CodeUri: src/lambda/list_datasets/
      Events:
        Auth:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /list-datasets
            Method: post # Should be get but fails, maybe something with permissions
      Layers:
        - !Ref Libraries
      Environment:
        Variables:
          CORS_ALLOW: !Ref CorsAllow
          USERS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
          DATASETS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref DatasetsTableName]]
          PROJECTS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref ProjectsTableName]]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
        - DynamoDBCrudPolicy:
            TableName:
              !Join ["-", [!Ref AWS::StackName, !Ref DatasetsTableName]]
        - DynamoDBCrudPolicy:
            TableName:
              !Join ["-", [!Ref AWS::StackName, !Ref ProjectsTableName]]

  SaveRegisterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    DependsOn:
      - UsersTable
      - DatasetsTable
      - DatasetsS3
    Properties:
      CodeUri: src/lambda/save_register/
      Events:
        Auth:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /save-register
            Method: post
      Layers:
        - !Ref Libraries
      Timeout: 300
      Environment:
        Variables:
          CORS_ALLOW: !Ref CorsAllow
          N_VERSIONS: !Ref NVersions # S3 implmentation
          USERS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
          DATASETS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref DatasetsTableName]]
          DATASETS_S3_BUCKET: # S3 implementation
            !Join ["-", [!Ref AWS::StackName, !Ref DatasetsS3Bucket]]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
        - DynamoDBCrudPolicy:
            TableName:
              !Join ["-", [!Ref AWS::StackName, !Ref DatasetsTableName]]
        - S3CrudPolicy: # S3 implementation
            BucketName:
              !Join ["-", [!Ref AWS::StackName, !Ref DatasetsS3Bucket]]

  LoadRegisterFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    DependsOn:
      - UsersTable
      - DatasetsTable
      - DatasetsS3
    Properties:
      CodeUri: src/lambda/load_register/
      Events:
        Auth:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /load-register
            Method: post
      Layers:
        - !Ref Libraries
      Timeout: 300
      Environment:
        Variables:
          CORS_ALLOW: !Ref CorsAllow
          USERS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
          DATASETS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref DatasetsTableName]]
          DATASETS_S3_BUCKET: # S3 implementation
            !Join ["-", [!Ref AWS::StackName, !Ref DatasetsS3Bucket]]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
        - DynamoDBCrudPolicy:
            TableName:
              !Join ["-", [!Ref AWS::StackName, !Ref DatasetsTableName]]
        - S3CrudPolicy: # S3 implementation
            BucketName:
              !Join ["-", [!Ref AWS::StackName, !Ref DatasetsS3Bucket]]

  SaveProjectFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    DependsOn:
      - UsersTable
      - ProjectsTable
    Properties:
      CodeUri: src/lambda/save_project/
      Events:
        Auth:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /save-project
            Method: post
      Layers:
        - !Ref Libraries
      Environment:
        Variables:
          CORS_ALLOW: !Ref CorsAllow
          USERS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
          PROJECTS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref ProjectsTableName]]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
        - DynamoDBCrudPolicy:
            TableName:
              !Join ["-", [!Ref AWS::StackName, !Ref ProjectsTableName]]

  ListProjectsFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    DependsOn:
      - UsersTable
      - ProjectsTable
    Properties:
      CodeUri: src/lambda/list_projects/
      Events:
        Auth:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /list-projects
            Method: post
      Layers:
        - !Ref Libraries
      Environment:
        Variables:
          CORS_ALLOW: !Ref CorsAllow
          USERS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
          PROJECTS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref ProjectsTableName]]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
        - DynamoDBCrudPolicy:
            TableName:
              !Join ["-", [!Ref AWS::StackName, !Ref ProjectsTableName]]

  RDSLambdaSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Lambda Function Security Group"
      VpcId: !Ref VPCId

  RDSInsertFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: src/lambda/rds_proxy/
      VpcConfig:
        SecurityGroupIds:
          - !Ref RDSLambdaSG
        SubnetIds: !Split [",", !Ref SubnetIDs]
      Events:
        Auth:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /rds-proxy
            Method: post
      Layers:
        - !Ref Libraries
        - !Ref Database
      Environment:
        Variables:
          CORS_ALLOW: !Ref CorsAllow
          HOST: !Ref Host
          PORT: !Ref Port
          DATABASE: !Ref Database
          USERNAME: !Ref Username
          USERS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
      Policies:
        - AWSLambdaVPCAccessExecutionRole
        - DynamoDBCrudPolicy:
            TableName: !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
        - Statement:
            - Effect: Allow
              Action:
                - rds-db:connect
              Resource: arn:aws:rds-db:us-east-2:560812044035:dbuser:prx-032739f4f5a366ac1/* #TODO Make specific

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PharosApi:
    Description: "API Endpoint:"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  UsersTableName:
    Description: "Users Table Name"
    Value: !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
  # AuthFunctionIamRole:
  #   Description: "Implicit IAM Role created for Fake Auth function"
  #   Value: !GetAtt AuthFunction.Arn
