AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  pharos-api

  Sample SAM Template for pharos-api

Parameters:
  CorsAllow:
    Type: String
    Default: "http://localhost:8000"
  UsersTableName:
    Type: String
    Default: "users"

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
    Tracing: Active
    Runtime: python3.9
    Architectures:
      - x86_64
    Handler: app.lambda_handler
  Api:
    Cors: !Join ["", ["'", !Ref CorsAllow, "'"]]
    TracingEnabled: True

Resources:
  # UsersTable:
  #   Type: AWS::DynamoDB::Table
  #   Properties:
  #     AttributeDefinitions:
  #       - AttributeName: "researcherID"
  #         AttributeType: "S"
  #     KeySchema:
  #       - AttributeName: "researcherID"
  #         KeyType: "HASH"
  #     ProvisionedThroughput:
  #       ReadCapacityUnits: 5
  #       WriteCapacityUnits: 5
  #     TableName: !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]

  AuthFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: auth/
      Events:
        Auth:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /auth
            Method: post
      Environment:
        Variables:
          CORS_ALLOW: !Ref CorsAllow
          USERS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]

  CreateUserFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: create_user/
      Events:
        Auth:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /create-user
            Method: post
      Environment:
        Variables:
          CORS_ALLOW: !Ref CorsAllow
          USERS_TABLE_NAME:
            !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  PharosApi:
    Description: "API Endpoint:"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  UsersTableName:
    Description: "Users Table Name"
    Value: !Join ["-", [!Ref AWS::StackName, !Ref UsersTableName]]
  # AuthFunctionIamRole:
  #   Description: "Implicit IAM Role created for Fake Auth function"
  #   Value: !GetAtt AuthFunction.Arn
