version: 2.1

credentials: &credentials
  - AWS Credentials

orbs:
  sam: circleci/aws-sam-serverless@3.2.0

workflows:
  version: 2
  build:
    jobs:
      # dev
      - deploy:
          config-env: dev
          context: *credentials
          filters:
            branches:
              only:
                - dev

      # prod
      - deploy:
          config-env: prod
          context: *credentials
          filters:
            branches:
              only:
                - prod

jobs:
  deploy:
    executor: sam/default

    parameters:
      config-env:
        type: string

    steps:
      - checkout
      - sam/install
      - run: sam deploy --config-env <<parameters.config-env>> --no-confirm-changeset
