version: 2.1

credentials: &credentials
  - AWS Credentials

# orbs:
#   sam: circleci/aws-sam-serverless@3.2.0
orbs:
  sam: circleci/aws-sam-serverless@4.0

workflows:
  version: 2
  build:
    jobs:
      # dev
      - deploy:
          config-env: dev
          context: *credentials
          filters:
            branches:
              only:
                - dev
                - feature/new-models

      # review
      - deploy:
          config-env: review
          context: *credentials
          filters:
            branches:
              only:
                - review

      # staging
      - deploy:
          config-env: staging
          context: *credentials
          filters:
            branches:
              only:
                - staging

      # prod
      - deploy:
          config-env: prod
          context: *credentials
          filters:
            branches:
              only:
                - prod

jobs:
  deploy:
    executor: sam/default

    parameters:
      config-env:
        type: string

    steps:
      - checkout

      - run:
          name: Install Python@3.9
          command: |
            sudo apt install software-properties-common;
            sudo add-apt-repository -y ppa:deadsnakes/ppa;
            sudo apt -y update;
            sudo apt -y install python3.9;
            sudo apt -y install python3.9-distutils;
            sudo apt -y install python3.9-venv;

      - run:
          name: Create virtualenv and install dev dependencies
          command: |
            python3.9 -m venv env .
            source env/bin/activate
            pip install -r dev-requirements.txt

      - run:
          name: Install NodeJS & Pyright
          command: |
            sudo apt install nodejs;
            npm install --global pyright;

      - run:
          name: Run Type Checks
          command: pyright

      - run:
          name: Run Tests
          command: |
            mkdir test-results
            pytest --junitxml=test-results/junit.xml

      - store_test_results:
          path: test-results

      - sam/install
      - run: sam build
      - run: |
          sam deploy \
            --config-env <<parameters.config-env>> \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
