version: 2.1

credentials: &credentials
  - AWS Credentials

orbs:
  sam: circleci/aws-sam-serverless@3.2.0

workflows:
  version: 2
  build:
    jobs:
      # dev
      - deploy:
        stack-name: pharos-api-dev
        parameter-overrides: CorsAllow=https://dev-pharos-frontend.talusanalytics.com
        filters:
          branches:
            only:
              - dev

jobs:
  deploy:
    working_directory: ~/repo

    docker:
      - image: cimg/node:lts

    parameters:
      stack-name:
        type: string
      parameter-overrides:
        type: string

    steps:
      - sam/deploy:
          context: *credentials
          stack-name: <<parameters.stack-name>>
          parameter-overrides: <<parameters.parameter-overrides>>
          template: ./template.yaml
