version: 2.1

credentials: &credentials
  - AWS Credentials

# orbs:
#   sam: circleci/aws-sam-serverless@3.2.0
orbs:
  sam: circleci/aws-sam-serverless@4.0

workflows:
  version: 2
  build:
    jobs:
      # dev
      - deploy:
          config-env: dev
          context: *credentials
          filters:
            branches:
              only:
                - dev

      # review
      - deploy:
          config-env: review
          context: *credentials
          filters:
            branches:
              only:
                - review

      # staging
      - deploy:
          config-env: staging
          context: *credentials
          filters:
            branches:
              only:
                - staging

      # prod
      - deploy:
          config-env: prod
          context: *credentials
          filters:
            branches:
              only:
                - prod

jobs:
  deploy:
    executor: sam/default

    parameters:
      config-env:
        type: string

    docker:
      - image: cimg/python:3.9

    steps:
      - checkout
      - sam/install
      - run: sam build
      - run: |
          sam deploy \
            --config-env <<parameters.config-env>> \
            --template-file ./template.yaml \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset
