version: 2.1

credentials: &credentials
  - AWS Credentials

orbs:
  sam: circleci/aws-sam-serverless@3.2.0

workflows:
  version: 2
  build:
    jobs:
      # dev
      - sam/deploy:
          stack-name: pharos-api-dev
          parameter-overrides: CorsAllow=https://dev-pharos-frontend.talusanalytics.com
          template: ./template.yaml
          context: *credentials
          filters:
            branches:
              only:
                - dev

      # - deploy:
      #     stack-name: pharos-api-dev
      #     parameter-overrides: CorsAllow=https://dev-pharos-frontend.talusanalytics.com
      #     context: *credentials
      #     filters:
      #       branches:
      #         only:
      #           - dev

      # - deploy:
      #     # Examples:
      #     # bucket: 's3://dev-projectname'
      #     # distribution: 'E31RXXXXXXXXXX'
      #     bucket: "s3://dev-pharos-frontend"
      #     distribution: "EWN5TGLCXWM1V"
      #     context: *credentials
      #     filters:
      #       branches:
      #         only:
      #           - dev
# jobs:
#   deploy:
#     working_directory: ~/repo

#     docker:
#       - image: cimg/node:lts

#     parameters:
#       stack-name:
#         type: string
#       parameter-overrides:
#         type: string

#     steps:
#       - sam/deploy:
#           stack-name: <<parameters.stack-name>>
#           parameter-overrides: <<parameters.parameter-overrides>>
#           template: ./template.yaml
