version: 2.1

credentials: &credentials
  - AWS Credentials

orbs:
  sam: circleci/aws-sam-serverless@3.2.0

workflows:
  version: 2
  build:
    jobs:
      # dev
      - deploy:
          config-env: dev
          context: *credentials
          filters:
            branches:
              only:
                - dev

      # review
      - deploy:
          config-env: review
          context: *credentials
          filters:
            branches:
              only:
                - reveiw

jobs:
  deploy:
    executor: sam/default

    parameters:
      config-env:
        type: string

    steps:
      - checkout
      - sam/install
      - run: |
          sam deploy \
            --config-env <<parameters.config-env>> \
            --template-file ./template.yaml \
            --no-confirm-changeset
